#
# bundler can't require gems from gemspec. So we need this crutch
#
require 'russian'
require 'jquery-rails'
require 'jquery-ui-rails'
require 'rails_sortable'
require 'awesome_nested_set'
require 'the_sortable_tree'
require 'administrate'
require 'administrate/field/date_picker'
require 'administrate/field/password'
require 'ckeditor'
require 'pundit'
require 'devise'
require 'carrierwave'
require 'pg_search'
require 'font-awesome-rails'
require 'meta-tags'
require 'friendly_id'
require 'babosa'